### ISSUE TITLE
Arabic/joining character formation broken

### ISSUE THREAD

**Issue by btsimonh** [sandflow/imscJS#109]
Ref branch 1.1-master:
The scheme for padding (and multi-row-align?) puts every character in it's own span.  On webkit based browsers, this causes the arabic character formation to be broken.

in the attached Arabitest.ttml sample, the characters should join, i.e. 
![image](https://user-images.githubusercontent.com/3137332/41144011-4c43da0c-6af3-11e8-98e0-81d66fb3c794.png)
should look like:
![image](https://user-images.githubusercontent.com/3137332/41144040-650c3084-6af3-11e8-94cf-6056450af29e.png)
or even like
![image](https://user-images.githubusercontent.com/3137332/41144063-7bd19cdc-6af3-11e8-9d27-b64f66c6b82d.png)
(the third image is from iexplore)

personally, I think the third display will be too difficult to achieve consistently across all browsers and renderers, and would be happy to caveat joining character sets in the standard to indicate that characters in different spans will specifically NOT join (but we may then need to MAKE them not join in iexplore).  Especially as they do not join in iexplore if styling is more different than just color?

[Arabictest.zip](https://github.com/sandflow/imscJS/files/2083267/Arabictest.zip)

**Comment by palemieux** [comment]
@btsimonh It would be possible to merge single-character spans after line wrapping is determined. I am thinking this would not help in this case since the merging of the spans would result in the arabic text being shorter (due to ligatures), and thus in changes to line wrapping. I am not sure how to work around this. Thoughts?

**Comment by btsimonh** [comment]
You are correct.  For wordwrapping, the length of the already-joined words must be taken into account; certainly in arabic/farsi, character lengths can vary wildly depending upon how they join.

see processLinePaddingAndMultiRowAlign in [my fork](https://github.com/btsimonh/imscJS/blob/rtl-MultiRowAlign-Padding/src/main/js/html.js)
(and a lot of the code above it) for a relatively complex implementation which separates all the words first, then apportions them to 'lines', reforming them into combined spans, before finally adding padding to the 'end' spans.  I don't think I finally got the rtl 'start' and 'end' spans identified correctly yet.  I prefer a 'simple' html output :).  This does rely on being able to measure the words....  but I assume this is also true of the single character method.

**Comment by palemieux** [comment]
@btsimonh Ok, so the idea is to create spans only where line wrap can actually happen? If so, what is a good reference for line breaks in arabic, i.e. where does the algorithm come from?

**Comment by palemieux** [comment]
The more I think about it, the more I think this is a [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=6148) that needs to be fixed there: imscJS should not have to implement line breaking algorithms.

Within the scope of 1.0.1 release, arabic ligature should work as long as `span` is not present within arabic text, and neither `ebutts:linePadding`, `ebutts:multiRowAlign`, nor `tts:fillLineGap` are used on `p` that contain arabic text.

For the next release, it should be possible to improve the imscJS line wrap detection algorithm so that `ebutts:linePadding`, `ebutts:multiRowAlign`, and `tts:fillLineGap` can be used.

In any case, I encourage users to file issues against WebKit.

**Comment by nigelmegitt** [comment]
#216 is partially relevant here: it merges adjacent character spans where they are 1) on the same line and 2) have the same parent element in the ISD. That demonstrably helps with the arabic character formation within a span, but can not address it across span boundaries, which as has been mentioned, appears to be a user agent bug.

**Comment by btsimonh** [comment]
Hi Nigel,
note the thing about the wrapping point changing when the span merging causes a change to the glyphs due to character joining.
I've not tested the original webkit bug recently.  I assume there is no improvement? 
br, simon hailes

**Comment by nigelmegitt** [comment]
> note the thing about the wrapping point changing when the span merging causes a change to the glyphs due to character joining.

@btsimonh Not sure exactly what you mean here? Yes, the rendered line length can change when characters are joined correctly, which happens when spans are merged. And yes, there is an edge case where that _could_ cause the wrapping to be different. I suppose one option would be to force the wrapping to stay the same, for example by setting CSS properties like `white-space: nowrap;` and `word-break: keep-all;` on each merged span.

Do you have a test case that demonstrates this issue?

> I've not tested the original webkit bug recently. I assume there is no improvement?

I haven't tested for it either. However I was slightly surprised to see that the joining character formation was fixed by #216 on Firefox on Mac OS: I had the impression that Firefox did not exhibit this behaviour, but that could have been me misremembering.
