### ISSUE TITLE
Difference bewteen TTML2 Shear Calculations and actual imscJS implementation

### ISSUE THREAD

**Issue by dtatut** [sandflow/imscJS#149]
In TTML2, 10.4.5.3 Shear Calculations use the trigonometric function tangent to generate the shear matrix. imscJS uses arc sinus. Any reason for this difference? The visual result is obviously not the same depending on what function you use.

**Comment by palemieux** [comment]
In TTML2, shear is specified as a percentage, but the (normative) mathematical transform is expressed as a 2D matrix transformation which uses the tangent of the shear angle.

As it turns out, TTML2 does not specify how to convert from the shear percentage to the shear angle. An [issue](https://github.com/w3c/ttml2/issues/1075) has been filed.

imscJS currently uses _shear_percentage = sin(shear_angle)_ although it is not clear why -- probably some historical  reason.

It is likely that the correct conversion is  _shear_percentage = shear_angle * 100 / 90_

The (relatively) good news is that sin(x) is approximately equal to x for small x. 

Thanks for the catch!
