### ISSUE TITLE
Add back support for fontShear

### ISSUE THREAD

**Issue by hans-pragt** [sandflow/imscJS#208]
Hi!

It seems that at some point in time this package had support for `fontShear` but that this was then replaced with `shear`. However, these apply to different elements as far as I can tell?

**Comment by palemieux** [comment]
During its development, IMSC 1.1 had briefly supported `tts:fontShear`, which was ultimately replaced by `tts:shear` before publication:

https://github.com/w3c/imsc/issues/401

Can you share what are you trying to do that `tts:shear` does not support?

**Comment by hans-pragt** [comment]
I would like to shear a `span`, not a `p`.

**Comment by palemieux** [comment]
@hans-pragt Are you looking to shear to a precise angle, or merely shear?

**Comment by hans-pragt** [comment]
An arbitrary angle.

**Comment by palemieux** [comment]
@hans-pragt Thanks for the detail. I recommend that, as a next step, you file an issue against IMSC at https://github.com/w3c/imsc since imscJS is intended to implement IMSC. The issue should ideally include sample renders illustrating the effect you are trying to achieve. Note that, at this time, only Firefox seems to support the `<angle>` option of `font-style: oblique`: https://developer.mozilla.org/en-US/docs/Web/CSS/font-style

**Comment by hans-pragt** [comment]
Okay, thanks!
