### ISSUE TITLE
linePadding not working on all lines

### ISSUE THREAD

**Issue by nigelmegitt** [sandflow/imscJS#27]
Rendering the example at http://bbc.github.io/subtitle-guidelines/codesamples/ebu-tt-d_example.xml the image at 10s appears as:

![10](https://cloud.githubusercontent.com/assets/4988915/21816855/84ab6358-d759-11e6-9234-c5e99d6fb919.png)

`ebutts:linePadding` is set to `"0.5c"` in this example but this is not being correctly honoured on the right end of the first line.

**Comment by nigelmegitt** [comment]
By the way, I should add that this is on Chrome - it works fine on Firefox.

**Comment by palemieux** [comment]
It looks like this is a symptom of a bug in Chrome, which does not suppress white-space at the end of lines. As a result, the newline before the `<br>` is turned into a space, which is wrapped in an anonymous span with a transparent background. It is the latter to which line padding is applied.

**Comment by nigelmegitt** [comment]
I understand, that certainly is unfortunate. Would you consider adding a workaround to "force" correct white space removal?

If you use jquery, something like the [`.trim()`](https://api.jquery.com/jQuery.trim/) feature applied to each line might work, for example.

**Comment by bbcrddave** [comment]
Is there a crbug ticket for this issue?

**Comment by palemieux** [comment]
> If you use jquery, something like the .trim() feature applied to each line might work, for example.

It is more complicated:

- hiding the spaces can only happen after the line breaks are determined through inspection (since lines can wrap)
- hiding the spaces can impact line wrap (in Chrome and Edge due to the bug)

... so this will need to be incorporated in the linePadding/multiRowAlign algorithm.

What would you day is the relative importance of this issue?

**Comment by palemieux** [comment]
@bbcrddave The thread at https://lists.w3.org/Archives/Public/www-style/2016Aug/0057.html implies that bugs would/should/could be filed.

**Comment by nigelmegitt** [comment]
> What would you day is the relative importance of this issue?

This is a tricky question to answer: relative to what? I would say that if linePadding is to be supported then it needs to be correctly supported, and it is something that I expect will be used.

Regarding the spaces impacting line wrap, if you know where the line wrap has been placed and that there is no manual break in the content, presumably you could in the script insert a `<br/>` so that any space trimming no longer affects the line breaks? And then trim trailing spaces.

**Comment by palemieux** [comment]
> if you know where the line wrap has been placed and that there is no manual break in the content,
> presumably you could in the script insert a <br/> so that any space trimming no longer affects the line breaks?

Yes, as long as removing the offending whitespace in Chrome would have not caused lines to re-wrap, at which point the explicit `<br/>` are no longer accurate.

The linePadding algorithm, which inserts explicit `<br/>` accounting for the extra space taken by the padding, can likely be modified to address this Chrome bug.  Modification of this algorithm however needs to be done carefully so that linePadding and multiRowAlign remain unaffected.

My plan is to first setup a robust test suite (see #29) and then address this kind of issues (with the safety net of a test suite to catch regression bugs) -- so the more tests the better at this point!

**Comment by bbcrddave** [comment]
Has there been any progress on this issue? I tried with Canary (60) and it is still a problem :cry:

**Comment by palemieux** [comment]
@bbcrddave Yes, #29 has been closed, so we can hopefully make progress on this one. Do you have a set of canonical linePadding/multiRowAlign tests that you use?

**Comment by palemieux** [comment]
@bbcrddave Something that could be done in the short-term is remove all whitespace before all explicit `<br>` before processing multiRowAlign and linePadding. It might not address all corner cases, but would address the test case above. Thoughts?

**Comment by nigelmegitt** [comment]
I haven't looked too hard at what it would take to create a bunch of canonical tests for this but they wouldn't really be about linePadding or multiRowAlign in themselves: rather they would be about the treatment of white space, since from https://github.com/sandflow/imscJS/issues/27#issuecomment-275025928 we can see that it is the presence of white space in particular locations that triggers the issue.

**Comment by palemieux** [comment]
@bbcrddave The PR at #40 should correct this defect following the . Looking forward to your review.

**Comment by bbcrddave** [comment]
Apologies for the slow response.
The proposed change solves the issue in Chrome and still works in Firefox - thanks!
