### ISSUE TITLE
Add support for smpte:image

### ISSUE THREAD

**Issue by nicosang** [sandflow/imscJS#8]
Hi,

I try to use the image profile with the attached sample.
[image_subtitle.zip](https://github.com/sandflow/imscJS/files/641919/image_subtitle.zip)

In the imgResolver function of the renderHTML function, the uri parameter is set to smpte:backgroundImage value. How can I get the smpte:image information with this parameter? Maybe, it's not really an issue...

Thanks,
Nicolas

**Comment by TobbeEdgeware** [comment]
The smpte:image attribute is prohibited by IMSC, so the only way is to use a URL. The preferred way, and the only way specified in CMAF, is to have the images included as subsamples in the same sample as the TTML.

However, I'd like this library to support embedded image data since we currently have that support in dash.js and it is part of the SMPTE-TT specification. 

@palemieux Can you add the possibility to extract the `<smpte:image>` element or whatever is needed to support this case, if it is not already available?

**Comment by nicosang** [comment]
once again thanks for the answer, if it's prohibited by IMSC....it's prohibited. ;-) I didn't have this information...

**Comment by palemieux** [comment]
@TobbeEdgeware What about providing a callback for element/attributes that are not recognized by imscJS? In particular, the caller would be given the opportunity to generate a data URL from `smpte:image` elements, which could be passed back to imscJS through the `imgResolver'.

**Comment by TobbeEdgeware** [comment]
@palemieux Sounds like a good solution.

**Comment by TobbeEdgeware** [comment]
@palemieux Did you implement the callback you mentioned above. It is still relevant for smpte:image.

**Comment by palemieux** [comment]
@TobbeEdgeware Will work on it today.

**Comment by palemieux** [comment]
@TobbeEdgeware Can you provide a test case?

**Comment by TobbeEdgeware** [comment]
I have two side loaded TTML files which I use in http://vm2.dashif.org/dash/vod/testpic_2s/img_subs.mpd

They  are
http://vm2.dashif.org/dash/vod/testpic_2s/img_swe.ttml
and
http://vm2.dashif.org/dash/vod/testpic_2s/img_subs_div.xml

**Comment by palemieux** [comment]
@TobbeEdgeware Thanks!

Both files are invalid, by the way, since `<metadata>` needs to appear immediately after `<head>`.

**Comment by TobbeEdgeware** [comment]
@palemieux OK. I fixed the last one. Will try to fix the first one as well. Thanks.

**Comment by palemieux** [comment]
@TobbeEdgeware See #47
